# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=2.4.0
maven_group=b100
archives_base_name=borderless-fullscreen

# Dependencies
fabric_api_version=0.144.0+26.1
modmenu_version=18.0.0-alpha.6
sodium_version=mc26.1-0.8.7-fabric
b100lib_version=0.2.3-26.1